### PR TITLE
Kitchen Mission - Further Small Polish

### LINKED ISSUE #275: Integrate world position arrow for kitchen mission

### LINKED ISSUE #287: Send all kitchen mission enemies to the break room once mission is over + make interactable
Talking about how rough the lunchtime rush was, and talking about maybe seeing someone around the kitchen (Birdie).

### LINKED ISSUE #323: Lock the doors to the garden during the tutorial
Maybe also do a funny self-conversation as well... rare case that users will try to do this though

### LINKED ISSUE #333: add chef asset + animations for kitchen mission
https://drive.google.com/drive/folders/1tNA6deZvMSSnnUgQ5pfeST2ycZgeAf3U

### PR DESCRIPTION
**Pull request by jurcaua**
Done currently:
* integrate world pointer with the mission (point to NPC mission reciever after collecting dentures)
* start kitchen enemies coming from the back room
* chef model and animations set up for final kitchen enemy
* locking doors from hallway to hedge, during tutorial + self autoplay convo for context

TODO:
* (waiting for my other PR to go in first because overlapping logic)
  * sending enemies to the back kitchen before deleting (or setting up with conversations maybe)

Resolves  #287 
Resolves #275
Resolves #323
Resolves #333

### CODE REVIEW

**Review by chadleytan — APPROVED** [review]
Don't see anything that could be an issue

**Review by fnnbrr — APPROVED** [review]
Everything looks good to me, no more getting spawn trapped in the dentures room!

I noticed that the kitchen quest giver NPC doesn't move from his original position & the potted plants don't disappear anymore. That's fine by me, but I just wanted to make sure that it was intentional & not just broken.

**Comment by jurcaua** [comment]
Yea, I intentionally just made him stay now, since that was causing issues, and going through the initial exit is essentially impossible now aha. Plants felt out of place too.

**Comment by fnnbrr** [comment]
@jurcaua everything works well for me, good to go.

**Review by chadleytan — COMMENTED** [review]
Found 2 bugs when playtesting:
* The awakeness meter disappeared when respawning after failing the last mission (Horrible screenshot LOL but maybe try it out as well cause it could just be my Unity)
Screen Shot 2020-04-09 at 4 29 52 PM

* Camera angle changes to the angle in Brutus' office if you run into the walls of the office
Screen Shot 2020-04-09 at 4 22 40 PM

**Comment by jurcaua** [comment]
> Found 2 bugs when playtesting:
> 
> * The awakeness meter disappeared when respawning after failing the last mission (Horrible screenshot LOL but maybe try it out as well cause it could just be my Unity)
>   Screen Shot 2020-04-09 at 4 29 52 PM
> * Camera angle changes to the angle in Brutus' office if you run into the walls of the office
>   Screen Shot 2020-04-09 at 4 22 40 PM

Ah, thank you sir!! @chadleytan 

1. Currently, the awakeness meter is not showing at all in the hedge maze area, so that's been logged and will be fixed in a future PR! (maybe you didn't realize the first time you entered the hedge maze that it was already not there?)

2. Ah, good catch! This seems to be both a bug with the CameraZone collider + the RegionManager not properly changing the camera back. Will look into this.

**Pull request merged**
