### PR TITLE
Kitchen Mission Start Interactable ZoomIn Cutscene

### LINKED ISSUE #94: Camera Zoom Into Interactable On Start of Mission - Mission 1 (Kitchen)

### PR DESCRIPTION
**Pull request by jurcaua**
interactable-focus-cutscene

* We have a prefab that has both the Cinemachine camera + a Dolly Track which defines the path the camera should go
  * We have an animator on the camera which will just update a variable slowly to move between different paths of the path (just a single float currently, 0 -> 2, since there are 2 nodes in the path).

* Also added Region Manager to support this feature
  * Just a manager with global references to different CameraZones

### CODE REVIEW

**Comment by fnnbrr** [comment]
Just tried it out, looks pretty slick!

Instead of the jump cut from the dentures --> Birdie, can you add either:
- a fade to black followed by a fade to Birdie's camera
- a camera pan back to Birdie?

that should make it feel less abrupt on the way back.

**Comment by jurcaua** [comment]
I like the fade best! I'll add that in!

Thanks @FinnbarrOC !

**Comment by jurcaua** [comment]
Updated and it looks like this now:
interactable-focus-cutscene2

**Comment by justineechen** [comment]
Woww it looks good! and it only happens the first time :)) nice dude!

**Review by justineechen — APPROVED** [review]

**Pull request merged**
