### PR TITLE
Music fixes

### PR DESCRIPTION
**Pull request by masonachu**
Created occlusion zones for music items using prefabs
- music in brutus office
- brutus voice
- music in garden
- piano does not play outside open free roam area
- radio does not play outside of room.

### CODE REVIEW

**Review by fnnbrr — CHANGES_REQUESTED** [review]
I found a few bugs; I'll post each one in a comment below.

**Comment by fnnbrr** [comment]
Bug 1:  Upon entering Brutus' office, there are two tracks playing at the same time.  Also, maybe tie the start of the music to the start of the cutscene vs. on entry to the door (since sometimes the player doesn't make it fully through the door before the cutscene starts).

**Comment by fnnbrr** [comment]
Bug 2:  Julian's maze music doesn't start playing the first time I enter the maze area, but it does work when I exit and re-enter after that.  Maybe just start that track as soon as the cutscene showing Brutus angry starts, and leave it to play the whole time until the end of the game.

**Comment by fnnbrr** [comment]
Bug 3:  Looks like the nurse door reference got unassigned in the RegionManager

image

**Comment by masonachu** [comment]
> Bug 1: Upon entering Brutus' office, there are two tracks playing at the same time. Also, maybe tie the start of the music to the start of the cutscene vs. on entry to the door (since sometimes the player doesn't make it fully through the door before the cutscene starts).

Hmm this one is strange because it doesn't relaunch another music track, rather it just turns it back on from the instance created from the kitchen mission. Will play around with it but can't get this specific bug on my end.

EDIT: Did run into the bug, the box collider in brutus room was just a tinyyy bit too small because of where Birdie stops when cutscene is triggered - maybe alex could look into starting a cutscene just a biiiit later in case, but should be fixed now.

What i did notice, however, is that after getting caught by brutus, the playerCaught param does not go back to 0f. the code is the following (in chaser.cs):

`                if (numChasersActive > 0)
                {
                    numChasersActive -= 1;
                    if (numChasersActive == 0)
                    {
                        // This means that the current chaser is the last to stop chasing Birdie
                        FMODUnity.RuntimeManager.StudioSystem.setParameterByName(playerChased, 0f);
                    }
                }
`
Finn, can I have you look at that?

**Comment by masonachu** [comment]
> Bug 2: Julian's maze music doesn't start playing the first time I enter the maze area, but it does work when I exit and re-enter after that. Maybe just start that track as soon as the cutscene showing Brutus angry starts, and leave it to play the whole time until the end of the game.

This should be fixed (there were overlapping zones) I wanted to make zones because I wanted to change the music when entering the hallway again - so if players go back and forth between areas the music will keep up with the changes. Will look into a better way to accomplish this though!

**Comment by masonachu** [comment]
> Bug 3: Looks like the nurse door reference got unassigned in the RegionManager
> 
> image

repaired in latest push!

**Comment by jurcaua** [comment]
Can't we have the music be based on the CameraZones we already have? That would make everything consistent with when the camera changes, when mission logic triggers on entering certain zones, etc.
All the logic for doing some action when a player enters a new zone is set up, so you could easily just hook it up by:
* adding some public variable to the `CameraZone` class, and then adding code in RegionManager for the function `HandleCurrentZone` to change the music to whatever the current zone is

**Comment by jurcaua** [comment]
Just jumped into the branch! Looks like CameraZone is actually being used mostly, my bad!
Maybe we should look into making the workout room and other areas separate? Rather than all being the "dining hall". Would be cleaner for the future. (granted, we may have to redo a lot of stuff anyways if we continue on the project)

**Comment by masonachu** [comment]
> Can't we have the music be based on the CameraZones we already have? That would make everything consistent with when the camera changes, when mission logic triggers on entering certain zones, etc.
> All the logic for doing some action when a player enters a new zone is set up, so you could easily just hook it up by:
> 
> * adding some public variable to the `CameraZone` class, and then adding code in RegionManager for the function `HandleCurrentZone` to change the music to whatever the current zone is

Totally!! that might be a better way to deal with it. We can look into that later

**Comment by masonachu** [comment]
> Just jumped into the branch! Looks like CameraZone is actually being used mostly, my bad!
> Maybe we should look into making the workout room and other areas separate? Rather than all being the "dining hall". Would be cleaner for the future. (granted, we may have to redo a lot of stuff anyways if we continue on the project)

Yeaaaah maybe we'll just glue things together for the time being to complete for itch.io submission and if we do move forward we'll have to rebuild and reevaluate for a longer playthrough anyways

**Comment by fnnbrr** [comment]
> > Bug 1: Upon entering Brutus' office, there are two tracks playing at the same time. Also, maybe tie the start of the music to the start of the cutscene vs. on entry to the door (since sometimes the player doesn't make it fully through the door before the cutscene starts).
> 
> Hmm this one is strange because it doesn't relaunch another music track, rather it just turns it back on from the instance created from the kitchen mission. Will play around with it but can't get this specific bug on my end.
> 
> EDIT: Did run into the bug, the box collider in brutus room was just a tinyyy bit too small because of where Birdie stops when cutscene is triggered - maybe alex could look into starting a cutscene just a biiiit later in case, but should be fixed now.
> 
> What i did notice, however, is that after getting caught by brutus, the playerCaught param does not go back to 0f. the code is the following (in chaser.cs):
> 
> ` if (numChasersActive > 0) { numChasersActive -= 1; if (numChasersActive == 0) { // This means that the current chaser is the last to stop chasing Birdie FMODUnity.RuntimeManager.StudioSystem.setParameterByName(playerChased, 0f); } }`
> Finn, can I have you look at that?

Yup that makes sense, I'll work on a fix.  I had patched up an issue related to this before, but I didn't think to include the FMOD param in that fix.

**Comment by fnnbrr** [comment]
Added my fix, but now I can't get through the door back into the nurse room at the very end of the game.  Did something get broken when you redid the door slam sfx?

**Comment by masonachu** [comment]
> Added my fix, but now I can't get through the door back into the nurse room at the very end of the game. Did something get broken when you redid the door slam sfx?

Hmm probably has something to do with the door hinge not opening the other direction during the tutorial mission? @jurcaua thoughts on this?

**Comment by jurcaua** [comment]
> > Added my fix, but now I can't get through the door back into the nurse room at the very end of the game. Did something get broken when you redid the door slam sfx?
> 
> Hmm probably has something to do with the door hinge not opening the other direction during the tutorial mission? @jurcaua thoughts on this?

Just set this reference and it should work!
image

**Review by fnnbrr — APPROVED** [review]

**Review by jurcaua — APPROVED** [review]

**Pull request merged**
